version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:13-3.1
    container_name: forest-db
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "4"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - forest-network

  # Backend API
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: forest-backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: geodb
      DB_USER: postgres
      DB_PASSWORD: "4"
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - forest-network
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: forest-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - forest-network
    volumes:
      - ./ssl:/etc/nginx/ssl:ro

  # Nginx Reverse Proxy (tùy chọn nếu cần load balancing)
  nginx:
    image: nginx:alpine
    container_name: forest-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - forest-network

volumes:
  postgres_data:
    driver: local

networks:
  forest-network:
    driver: bridge