# ============================================
# COMPLETE MAPSERVER FIX SCRIPT FOR WINDOWS
# ============================================
# Script nay se tu dong fix tat ca van de MapServer tren Windows Server
# Chay voi quyen Administrator trong PowerShell

param(
    [string]$ProjectPath = "C:\DuBaoMatRung",
    [string]$MS4WPath = "C:\ms4w\Apache\cgi-bin\mapserv.exe",
    [string]$PostgresPassword = "",
    [switch]$AutoRestart = $false
)

$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host "?  MAPSERVER COMPLETE FIX SCRIPT FOR WINDOWS                  ?" -ForegroundColor Cyan
Write-Host "?  Du Bao Mat Rung - LuckyBoiz Edition                       ?" -ForegroundColor Cyan
Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host ""

# ============================================
# STEP 0: Validate Project Path
# ============================================
Write-Host "[STEP 0] Validating project path..." -ForegroundColor Yellow
if (!(Test-Path $ProjectPath)) {
    Write-Host "   [ERROR] Project path not found: $ProjectPath" -ForegroundColor Red
    Write-Host "   Usage: .\fix-mapserver-complete.ps1 -ProjectPath 'D:\YourProjectPath'" -ForegroundColor Yellow
    exit 1
}
Write-Host "   [OK] Project path: $ProjectPath" -ForegroundColor Green

# ============================================
# STEP 1: Check MS4W Installation
# ============================================
Write-Host ""
Write-Host "[STEP 1] Checking MS4W installation..." -ForegroundColor Yellow
if (!(Test-Path $MS4WPath)) {
    Write-Host "   [ERROR] MS4W not found at: $MS4WPath" -ForegroundColor Red
    Write-Host ""
    Write-Host "   Please install MS4W first:" -ForegroundColor Yellow
    Write-Host "   1. Download from: https://ms4w.com/download.html" -ForegroundColor White
    Write-Host "   2. Extract to C:\ms4w\" -ForegroundColor White
    Write-Host "   3. Run this script again" -ForegroundColor White
    Write-Host ""
    Write-Host "   Or specify custom path: -MS4WPath 'D:\ms4w\Apache\cgi-bin\mapserv.exe'" -ForegroundColor Cyan
    exit 1
}
Write-Host "   [OK] MS4W found: $MS4WPath" -ForegroundColor Green

# Test MapServer binary
try {
    $testOutput = & $MS4WPath 2>&1
    Write-Host "   [OK] MapServer binary is executable" -ForegroundColor Green
} catch {
    Write-Host "   [WARNING] MapServer binary test failed, but will continue..." -ForegroundColor Yellow
}

# ============================================
# STEP 2: Create Required Directories
# ============================================
Write-Host ""
Write-Host "[STEP 2] Creating required directories..." -ForegroundColor Yellow

$directories = @(
    "$ProjectPath\mapserver\mapfiles",
    "$ProjectPath\mapserver\tmp",
    "$ProjectPath\mapserver\shapefiles",
    "$ProjectPath\microservices\services\mapserver-service"
)

foreach ($dir in $directories) {
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "   [CREATE] $dir" -ForegroundColor Green
    } else {
        Write-Host "   [OK] $dir" -ForegroundColor Gray
    }
}

# Set permissions for tmp directory
$tmpPath = "$ProjectPath\mapserver\tmp"
try {
    icacls $tmpPath /grant Everyone:F /T | Out-Null
    Write-Host "   [OK] Permissions set for tmp directory" -ForegroundColor Green
} catch {
    Write-Host "   [WARNING] Could not set permissions, may need manual fix" -ForegroundColor Yellow
}

# ============================================
# STEP 3: Create .env File
# ============================================
Write-Host ""
Write-Host "[STEP 3] Creating MapServer service .env file..." -ForegroundColor Yellow

$envPath = "$ProjectPath\microservices\services\mapserver-service\.env"
$mapfilePath = "$ProjectPath\mapserver\mapfiles\laocai.map"

# Convert paths to proper format for .env (Windows path with backslashes)
$ms4wPathForEnv = $MS4WPath -replace '\\', '\\'
$mapfilePathForEnv = $mapfilePath -replace '\\', '\\'

$envContent = @"
# MapServer Service Environment - Windows Configuration
# Auto-generated by fix-mapserver-complete.ps1

NODE_ENV=production
PORT=3008

# MapServer for Windows (MS4W)
MAPSERV_BIN=$MS4WPath
MAPFILE_PATH=$mapfilePath

# Logging
LOG_LEVEL=info

# Generated on: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

Set-Content -Path $envPath -Value $envContent -Force -Encoding UTF8
Write-Host "   [OK] Created: $envPath" -ForegroundColor Green
Write-Host "   MapServer Binary: $MS4WPath" -ForegroundColor Gray
Write-Host "   MapFile Path: $mapfilePath" -ForegroundColor Gray

# ============================================
# STEP 4: Check PostgreSQL
# ============================================
Write-Host ""
Write-Host "[STEP 4] Checking PostgreSQL service..." -ForegroundColor Yellow

$pgServices = Get-Service -Name "*postgresql*" -ErrorAction SilentlyContinue

if ($pgServices) {
    $pgService = $pgServices | Select-Object -First 1
    if ($pgService.Status -eq "Running") {
        Write-Host "   [OK] PostgreSQL is running ($($pgService.Name))" -ForegroundColor Green
    } else {
        Write-Host "   [WARNING] PostgreSQL is not running" -ForegroundColor Yellow
        Write-Host "   Attempting to start..." -ForegroundColor Yellow
        try {
            Start-Service $pgService.Name
            Start-Sleep -Seconds 2
            Write-Host "   [OK] PostgreSQL started" -ForegroundColor Green
        } catch {
            Write-Host "   [ERROR] Failed to start PostgreSQL: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
} else {
    Write-Host "   [WARNING] PostgreSQL service not found" -ForegroundColor Yellow
    Write-Host "   Please ensure PostgreSQL is installed and running" -ForegroundColor Yellow
}

# Test PostgreSQL connection
if ($PostgresPassword) {
    Write-Host "   Testing PostgreSQL connection..." -ForegroundColor Yellow
    $env:PGPASSWORD = $PostgresPassword
    try {
        $result = psql -U postgres -d admin_db -c "SELECT version();" 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "   [OK] PostgreSQL connection successful" -ForegroundColor Green
        } else {
            Write-Host "   [WARNING] PostgreSQL connection failed" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "   [WARNING] psql command not found in PATH" -ForegroundColor Yellow
    }
    Remove-Item Env:\PGPASSWORD
}

# ============================================
# STEP 5: Check MapFile
# ============================================
Write-Host ""
Write-Host "[STEP 5] Checking MapFile..." -ForegroundColor Yellow

if (Test-Path $mapfilePath) {
    Write-Host "   [OK] MapFile exists: $mapfilePath" -ForegroundColor Green

    # Read and validate basic MapFile structure
    $mapFileContent = Get-Content $mapfilePath -Raw
    if ($mapFileContent -match "MAP" -and $mapFileContent -match "END") {
        Write-Host "   [OK] MapFile structure looks valid" -ForegroundColor Green
    } else {
        Write-Host "   [WARNING] MapFile structure may be invalid" -ForegroundColor Yellow
    }

    # Check for Windows paths in MapFile
    if ($mapFileContent -match "/") {
        Write-Host "   [WARNING] MapFile contains Unix-style paths" -ForegroundColor Yellow
        Write-Host "   Consider updating paths to Windows format (C:\...)" -ForegroundColor Yellow
    }
} else {
    Write-Host "   [WARNING] MapFile not found: $mapfilePath" -ForegroundColor Yellow
    Write-Host "   You need to create or copy a MapFile before the service will work" -ForegroundColor Yellow
}

# ============================================
# STEP 6: Check Node.js and Dependencies
# ============================================
Write-Host ""
Write-Host "[STEP 6] Checking Node.js environment..." -ForegroundColor Yellow

$nodeVersion = node --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "   [OK] Node.js version: $nodeVersion" -ForegroundColor Green
} else {
    Write-Host "   [ERROR] Node.js not found!" -ForegroundColor Red
    Write-Host "   Please install Node.js from: https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

$npmVersion = npm --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "   [OK] NPM version: $npmVersion" -ForegroundColor Green
} else {
    Write-Host "   [ERROR] NPM not found!" -ForegroundColor Red
    exit 1
}

# Check dependencies
$serviceDir = "$ProjectPath\microservices\services\mapserver-service"
$packageJsonPath = "$serviceDir\package.json"

if (Test-Path $packageJsonPath) {
    Write-Host "   [OK] package.json found" -ForegroundColor Green

    $nodeModulesPath = "$serviceDir\node_modules"
    if (!(Test-Path $nodeModulesPath)) {
        Write-Host "   [WARNING] node_modules not found" -ForegroundColor Yellow
        Write-Host "   Installing dependencies..." -ForegroundColor Yellow
        Push-Location $serviceDir
        npm install
        Pop-Location
        if ($LASTEXITCODE -eq 0) {
            Write-Host "   [OK] Dependencies installed" -ForegroundColor Green
        } else {
            Write-Host "   [ERROR] Failed to install dependencies" -ForegroundColor Red
        }
    } else {
        Write-Host "   [OK] node_modules exists" -ForegroundColor Green
    }
} else {
    Write-Host "   [ERROR] package.json not found at: $packageJsonPath" -ForegroundColor Red
}

# ============================================
# STEP 7: Check PM2
# ============================================
Write-Host ""
Write-Host "[STEP 7] Checking PM2..." -ForegroundColor Yellow

$pm2Version = pm2 --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "   [OK] PM2 version: $pm2Version" -ForegroundColor Green

    # Check if mapserver-service is in PM2
    $pm2List = pm2 jlist | ConvertFrom-Json
    $mapserverProcess = $pm2List | Where-Object { $_.name -eq "mapserver-service" }

    if ($mapserverProcess) {
        Write-Host "   [OK] mapserver-service found in PM2" -ForegroundColor Green
        Write-Host "   Status: $($mapserverProcess.pm2_env.status)" -ForegroundColor Gray

        if ($AutoRestart) {
            Write-Host "   Restarting mapserver-service..." -ForegroundColor Yellow
            pm2 restart mapserver-service
            Start-Sleep -Seconds 2
            Write-Host "   [OK] Service restarted" -ForegroundColor Green
        }
    } else {
        Write-Host "   [INFO] mapserver-service not found in PM2" -ForegroundColor Cyan
        Write-Host "   Start it with: pm2 start ecosystem.config.js --only mapserver-service" -ForegroundColor White
    }
} else {
    Write-Host "   [WARNING] PM2 not found" -ForegroundColor Yellow
    Write-Host "   Installing PM2..." -ForegroundColor Yellow
    npm install -g pm2
    if ($LASTEXITCODE -eq 0) {
        Write-Host "   [OK] PM2 installed" -ForegroundColor Green
    } else {
        Write-Host "   [ERROR] Failed to install PM2" -ForegroundColor Red
    }
}

# ============================================
# STEP 8: Test Service Connectivity
# ============================================
Write-Host ""
Write-Host "[STEP 8] Testing service connectivity..." -ForegroundColor Yellow

# Test if service is listening on port 3008
$port3008 = Get-NetTCPConnection -LocalPort 3008 -ErrorAction SilentlyContinue
if ($port3008) {
    Write-Host "   [OK] Service is listening on port 3008" -ForegroundColor Green

    # Test health endpoint
    Start-Sleep -Seconds 1
    try {
        $healthResponse = Invoke-WebRequest -Uri "http://localhost:3008/health" -UseBasicParsing -TimeoutSec 5
        if ($healthResponse.StatusCode -eq 200) {
            Write-Host "   [OK] Health check passed" -ForegroundColor Green
            Write-Host "   Response: $($healthResponse.Content)" -ForegroundColor Gray
        }
    } catch {
        Write-Host "   [WARNING] Health check failed: $($_.Exception.Message)" -ForegroundColor Yellow
    }
} else {
    Write-Host "   [INFO] Service not running on port 3008" -ForegroundColor Cyan
    Write-Host "   Start the service and run test again" -ForegroundColor White
}

# ============================================
# STEP 9: Check Nginx Configuration
# ============================================
Write-Host ""
Write-Host "[STEP 9] Checking Nginx configuration..." -ForegroundColor Yellow

$nginxService = Get-Service -Name "Nginx" -ErrorAction SilentlyContinue
if ($nginxService) {
    if ($nginxService.Status -eq "Running") {
        Write-Host "   [OK] Nginx is running" -ForegroundColor Green
    } else {
        Write-Host "   [WARNING] Nginx is not running" -ForegroundColor Yellow
    }
} else {
    Write-Host "   [INFO] Nginx not found as a service" -ForegroundColor Cyan
}

# ============================================
# FINAL SUMMARY
# ============================================
Write-Host ""
Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Green
Write-Host "?                    SETUP SUMMARY                            ?" -ForegroundColor Green
Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Green
Write-Host ""

Write-Host "? MS4W Installation: " -NoNewline -ForegroundColor White
Write-Host "OK" -ForegroundColor Green

Write-Host "? Directories Created: " -NoNewline -ForegroundColor White
Write-Host "OK" -ForegroundColor Green

Write-Host "? .env Configuration: " -NoNewline -ForegroundColor White
Write-Host "OK" -ForegroundColor Green

Write-Host ""
Write-Host "? Next Steps:" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Verify MapFile exists and is valid:" -ForegroundColor White
Write-Host "   $mapfilePath" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Update PostgreSQL connection in MapFile (if needed)" -ForegroundColor White
Write-Host "   CONNECTION 'host=localhost port=5432 dbname=admin_db user=postgres password=YOUR_PASSWORD'" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Start/Restart the service:" -ForegroundColor White
Write-Host "   pm2 restart mapserver-service" -ForegroundColor Gray
Write-Host "   # or if not started yet:" -ForegroundColor Gray
Write-Host "   cd $ProjectPath" -ForegroundColor Gray
Write-Host "   pm2 start ecosystem.config.js --only mapserver-service" -ForegroundColor Gray
Write-Host ""
Write-Host "4. Test the service:" -ForegroundColor White
Write-Host "   .\scripts\windows\test-mapserver.ps1" -ForegroundColor Gray
Write-Host "   # or manually:" -ForegroundColor Gray
Write-Host "   curl http://localhost:3008/health" -ForegroundColor Gray
Write-Host ""
Write-Host "5. Check browser:" -ForegroundColor White
Write-Host "   http://103.56.160.66/api/mapserver?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities" -ForegroundColor Gray
Write-Host ""

Write-Host "? Troubleshooting:" -ForegroundColor Cyan
Write-Host "   - View logs: pm2 logs mapserver-service" -ForegroundColor White
Write-Host "   - Check status: pm2 status" -ForegroundColor White
Write-Host "   - Restart all: pm2 restart all" -ForegroundColor White
Write-Host "   - Check this file: $envPath" -ForegroundColor White
Write-Host ""

Write-Host "? Setup complete! Good luck, LuckyBoiz!" -ForegroundColor Green
Write-Host ""
